[workspace]
members = [
    "iora-shared",
    "iora-home",
    "iora-core",
    "iora-control",
    "iora-assist",
    "iora-secrets",
    "iora-watchdog",
    "iora-installer",
    "iora-security",
    "iora-gateway",
    "iora-files",
    "iora-connector",
    "iora-api",
    "iora-supervisor",
    "iora-cli",
    "iora-appstore",
    "iora-nginx",
    "iora-network-monitor",
]
resolver = "2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
