import { useCallback, useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { createPortal } from 'react-dom'
import { ArrowClockwise, CheckCircle, Database, FolderOpen, HardDrive, Pulse, ShareNetwork, Wrench, WarningCircle, X } from '@phosphor-icons/react'
import { authFetch } from '@/lib/authHelpers'
import { useVisibleInterval } from '@/hooks/useVisibleInterval'
import { OsAppNavbar } from '@/components/OsAppNavbar'

interface BlockDevice { name?: string; path?: string; type?: string; size?: number; model?: string; serial?: string; vendor?: string; tran?: string; rota?: boolean; rm?: boolean; ro?: boolean; fstype?: string; label?: string; mountpoints?: Array<string | null>; children?: BlockDevice[] }
interface RaidArray { name: string; active: boolean; level: string; members: string[]; blocks?: number; expected_devices?: number; active_devices?: number; health: 'healthy' | 'degraded' | 'inactive'; operation?: string; progress_percent?: number }
interface SmartData { smart_status?: { passed?: boolean }; temperature?: { current?: number }; model_name?: string; serial_number?: string; nvme_smart_health_information_log?: { percentage_used?: number; media_errors?: number } }
interface OperationPlan { operation: string; array?: string; resource?: string; summary: string; warnings: string[]; commands: Array<{ program: string; arguments: string[]; purpose: string }>; confirmation_phrase: string; executable: boolean }
interface Inventory { read_only: boolean; capabilities: Record<string, { available: boolean; detail: string }>; block_devices: BlockDevice[]; smart: Record<string, SmartData>; raid_arrays: RaidArray[] }
interface StoragePool { backend: string; name: string; health: string; size_bytes?: number; allocated_bytes?: number; free_bytes?: number; mount_points: string[] }
interface NasShare { protocol: string; name: string; path: string; read_only: boolean; guest_access: boolean; clients: string[]; valid_users: string[] }
interface NasInventory { read_only: boolean; pools: StoragePool[]; shares: NasShare[]; capabilities: Record<string, boolean> }
interface StorageJob { id: string; kind: string; resource: string; status: string; progress_percent: number; message: string; error?: string; created_at: string }

function formatBytes(value = 0) { const units = ['B', 'KB', 'MB', 'GB', 'TB', 'PB']; let amount = value; let index = 0; while (amount >= 1024 && index < units.length - 1) { amount /= 1024; index++ } return `${amount.toFixed(index ? 1 : 0)} ${units[index]}` }

export function OsStorageApp() {
  const { t } = useTranslation()
  const [inventory, setInventory] = useState<Inventory | null>(null)
  const [nasInventory, setNasInventory] = useState<NasInventory | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [planning, setPlanning] = useState(false)
  const [plan, setPlan] = useState<OperationPlan | null>(null)
  const [plannedRequest, setPlannedRequest] = useState<Record<string, unknown> | null>(null)
  const [confirmation, setConfirmation] = useState('')
  const [jobs, setJobs] = useState<StorageJob[]>([])
  const [volumeForm, setVolumeForm] = useState({ backend: 'btrfs', pool: '', name: '', quota: '' })
  const [shareForm, setShareForm] = useState({ protocol: 'smb', name: '', path: '', readOnly: false, guestAccess: false, principals: '' })
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [storageResponse, nasResponse, jobsResponse] = await Promise.all([authFetch('/api/os/control/os/storage/inventory'), authFetch('/api/os/control/os/storage/nas'), authFetch('/api/os/control/os/storage/jobs')]); if (!storageResponse.ok || !nasResponse.ok || !jobsResponse.ok) throw new Error(`HTTP ${storageResponse.status}/${nasResponse.status}/${jobsResponse.status}`); setInventory(await storageResponse.json()); setNasInventory(await nasResponse.json()); setJobs((await jobsResponse.json()).jobs || []) } catch { setError(t('storageApp.unavailable')) } finally { setLoading(false) } }, [t])
  useVisibleInterval(load, 5000)
  const reviewScrub = async (array: string) => { const request = { operation: 'scrub', array }; setPlanning(true); try { const response = await authFetch('/api/os/control/os/storage/raid/plan', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(request) }); if (!response.ok) throw new Error(await response.text()); setPlannedRequest(request); setConfirmation(''); setPlan(await response.json()) } catch { setError(t('storageApp.planFailed')) } finally { setPlanning(false) } }
  const reviewReplacement = async (array: string, replacement: string) => { const request = { operation: 'replace_member', array, failed_member: null, replacement }; setPlanning(true); try { const response = await authFetch('/api/os/control/os/storage/raid/plan', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(request) }); if (!response.ok) throw new Error(await response.text()); setPlannedRequest(request); setConfirmation(''); setPlan(await response.json()) } catch { setError(t('storageApp.replacementRejected')) } finally { setPlanning(false) } }
  const reviewNasPlan = async (body: Record<string, unknown>) => { setPlanning(true); setError(''); try { const response = await authFetch('/api/os/control/os/storage/nas/plan', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); if (!response.ok) throw new Error(await response.text()); setPlannedRequest(body); setConfirmation(''); setPlan(await response.json()) } catch { setError(t('storageApp.nasPlanFailed')) } finally { setPlanning(false) } }
  const executePlan = async () => { if (!plannedRequest || !plan) return; setPlanning(true); setError(''); try { const endpoint = plan.array ? '/api/os/control/os/storage/raid/execute' : '/api/os/control/os/storage/nas/execute'; const response = await authFetch(endpoint, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ request: plannedRequest, confirmation }) }); if (response.status === 401) throw new Error('fresh-auth'); if (!response.ok) throw new Error(await response.text()); setPlan(null); setPlannedRequest(null); setConfirmation(''); await load() } catch (executionError) { setError(executionError instanceof Error && executionError.message === 'fresh-auth' ? t('storageApp.freshAuthRequired') : t('storageApp.executionFailed')) } finally { setPlanning(false) } }

  const disks = inventory?.block_devices.filter((device) => device.type === 'disk') || []
  const degraded = inventory?.raid_arrays.filter((array) => array.health !== 'healthy').length || 0
  return <section className="rumahl-app-frame overflow-hidden">
    <OsAppNavbar pageId="os-storage" title={t('os.apps.storage.name')} description={t('os.apps.storage.description')} icon={<HardDrive size={24} weight="duotone" />} accent="oklch(0.68 0.16 205)" trailing={<><span className="rounded-full bg-cyan-500/10 px-3 py-1 text-xs text-cyan-300">{t('storageApp.readOnly')}</span><button type="button" onClick={() => void load()} disabled={loading} className="rumahl-icon-button" title={t('common.refresh')}><ArrowClockwise size={18} className={loading ? 'animate-spin' : ''} /></button></>} />
    <div className="p-4">
    {error && <div className="mb-4 rounded-2xl border border-destructive/20 bg-destructive/10 p-4 text-sm text-destructive">{error}</div>}
    <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Summary icon={HardDrive} label={t('storageApp.physicalDisks')} value={String(disks.length)} /><Summary icon={Database} label={t('storageApp.raidArrays')} value={String(inventory?.raid_arrays.length || 0)} /><Summary icon={degraded ? WarningCircle : CheckCircle} label={t('storageApp.raidHealth')} value={degraded ? t('storageApp.attention', { count: degraded }) : t('storageApp.healthy')} warning={degraded > 0} /><Summary icon={FolderOpen} label={t('storageApp.storagePools')} value={String(nasInventory?.pools.length || 0)} /><Summary icon={ShareNetwork} label={t('storageApp.nasShares')} value={String(nasInventory?.shares.length || 0)} /></div>

    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.4fr)_minmax(320px,1fr)]">
      <div className="space-y-3"><h2 className="text-sm font-semibold">{t('storageApp.disks')}</h2>{disks.map((disk) => { const smart = inventory?.smart[disk.path || '']; const passed = smart?.smart_status?.passed; return <article key={disk.path || disk.name} className="rumahl-card p-5"><div className="flex items-start gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-2xl bg-cyan-500/10 text-cyan-300"><HardDrive size={23} weight="duotone" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold">{disk.model || disk.name || t('storageApp.unknownDisk')}</h3><span className={`rounded-full px-2 py-1 text-[10px] ${passed === false ? 'bg-destructive/10 text-destructive' : passed === true ? 'bg-success/10 text-success' : 'bg-foreground/7 text-foreground/45'}`}>{passed === false ? t('storageApp.smartFailed') : passed === true ? t('storageApp.smartPassed') : t('storageApp.smartUnknown')}</span></div><p className="mt-1 text-xs text-foreground/40">{disk.path} · {disk.serial || t('storageApp.noSerial')}</p><div className="mt-4 grid grid-cols-2 gap-3 text-xs sm:grid-cols-4"><Metric label={t('storageApp.capacity')} value={formatBytes(disk.size)} /><Metric label={t('storageApp.transport')} value={disk.tran || '–'} /><Metric label={t('storageApp.temperature')} value={smart?.temperature?.current != null ? `${smart.temperature.current} °C` : '–'} /><Metric label={t('storageApp.media')} value={disk.rota ? 'HDD' : 'SSD/NVMe'} /></div>{disk.children?.length ? <div className="mt-4 border-t border-foreground/7 pt-3 text-xs text-foreground/50">{disk.children.map((child) => <div key={child.path} className="flex justify-between py-1"><span>{child.path} · {child.fstype || t('storageApp.unformatted')}</span><span>{formatBytes(child.size)}{child.mountpoints?.filter(Boolean).length ? ` · ${child.mountpoints.filter(Boolean).join(', ')}` : ''}</span></div>)}</div> : null}</div></div></article> })}{!loading && disks.length === 0 && <Empty text={t('storageApp.noDisks')} />}</div>
      <div className="space-y-3"><h2 className="text-sm font-semibold">{t('storageApp.raid')}</h2>{inventory?.raid_arrays.map((array) => <article key={array.name} className={`rumahl-card rounded-3xl border p-5 ${array.health === 'healthy' ? 'border-emerald-400/15' : 'border-amber-400/25'}`}><div className="flex items-center justify-between"><div><h3 className="font-semibold">/dev/{array.name}</h3><p className="text-xs uppercase text-foreground/40">{array.level}</p></div>{array.health === 'healthy' ? <CheckCircle size={24} className="text-success" /> : <WarningCircle size={24} className="text-warning" />}</div><div className="mt-4 grid grid-cols-2 gap-3"><Metric label={t('storageApp.state')} value={t(`storageApp.state_${array.health}`)} /><Metric label={t('storageApp.members')} value={`${array.active_devices ?? array.members.length}/${array.expected_devices ?? array.members.length}`} /><Metric label={t('storageApp.capacity')} value={formatBytes((array.blocks || 0) * 1024)} /><Metric label={t('storageApp.devices')} value={array.members.join(', ') || '–'} /></div>{array.operation && <div className="mt-4"><div className="mb-1 flex justify-between text-xs"><span>{t('storageApp.operation', { operation: array.operation })}</span><span>{array.progress_percent?.toFixed(1) || 0}%</span></div><div className="h-2 overflow-hidden rounded-full bg-foreground/8"><div className="h-full rounded-full bg-cyan-400" style={{ width: `${Math.min(array.progress_percent || 0, 100)}%` }} /></div></div>}{!array.operation && <div className="mt-4 flex flex-wrap gap-2"><button type="button" disabled={planning} onClick={() => void reviewScrub(array.name)} className="rumahl-secondary-button"><Pulse size={15} />{t('storageApp.reviewScrub')}</button>{array.health === 'degraded' && disks.filter((disk) => !disk.mountpoints?.some(Boolean) && !disk.children?.some((child) => child.mountpoints?.some(Boolean))).map((disk) => <button type="button" key={disk.path} disabled={planning} onClick={() => disk.path && void reviewReplacement(array.name, disk.path)} className="rumahl-secondary-button"><Wrench size={15} />{t('storageApp.reviewReplacement', { device: disk.path })}</button>)}</div>}</article>)}{!loading && !inventory?.raid_arrays.length && <Empty text={t('storageApp.noRaid')} />}<div className="rumahl-card p-5"><h3 className="mb-3 flex items-center gap-2 text-sm font-semibold"><Pulse size={18} />{t('storageApp.capabilities')}</h3>{Object.entries(inventory?.capabilities || {}).map(([name, capability]) => <div key={name} className="flex items-center justify-between border-b border-foreground/6 py-2 text-xs last:border-0"><span>{name}</span><span className={capability.available ? 'text-success' : 'text-foreground/35'}>{capability.available ? t('storageApp.available') : t('storageApp.notAvailable')}</span></div>)}</div></div>
    </div>
    <div className="mt-5 grid gap-5 xl:grid-cols-2">
      <div className="space-y-3"><h2 className="text-sm font-semibold">{t('storageApp.storagePools')}</h2>{nasInventory?.pools.map((pool) => <article key={`${pool.backend}-${pool.name}`} className="rumahl-card p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{pool.name}</h3><p className="text-xs uppercase text-foreground/40">{pool.backend}</p></div><span className="rounded-full bg-success/10 px-2 py-1 text-[10px] text-success">{pool.health}</span></div><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3"><Metric label={t('storageApp.capacity')} value={pool.size_bytes != null ? formatBytes(pool.size_bytes) : '–'} /><Metric label={t('storageApp.free')} value={pool.free_bytes != null ? formatBytes(pool.free_bytes) : '–'} /><Metric label={t('storageApp.mountPoints')} value={pool.mount_points.join(', ') || '–'} /></div></article>)}{!loading && !nasInventory?.pools.length && <Empty text={t('storageApp.noPools')} />}</div>
      <div className="space-y-3"><h2 className="text-sm font-semibold">{t('storageApp.nasShares')}</h2>{nasInventory?.shares.map((share) => <article key={`${share.protocol}-${share.name}-${share.path}`} className="rumahl-card p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{share.name}</h3><p className="text-xs text-foreground/40">{share.path}</p></div><span className="rounded-full bg-cyan-500/10 px-2 py-1 text-[10px] uppercase text-cyan-300">{share.protocol}</span></div><div className="mt-4 grid grid-cols-2 gap-3"><Metric label={t('storageApp.accessMode')} value={share.read_only ? t('storageApp.shareReadOnly') : t('storageApp.readWrite')} /><Metric label={t('storageApp.guestAccess')} value={share.guest_access ? t('storageApp.enabled') : t('storageApp.disabled')} /><Metric label={t('storageApp.clients')} value={share.clients.join(', ') || '–'} /><Metric label={t('storageApp.validUsers')} value={share.valid_users.join(', ') || '–'} /></div></article>)}{!loading && !nasInventory?.shares.length && <Empty text={t('storageApp.noShares')} />}</div>
    </div>
    <div className="mt-5 grid gap-5 xl:grid-cols-2">
      <form className="rumahl-card p-5" onSubmit={(event) => { event.preventDefault(); void reviewNasPlan({ operation: 'create_volume', backend: volumeForm.backend, pool: volumeForm.pool, name: volumeForm.name, quota_bytes: volumeForm.quota ? Number(volumeForm.quota) * 1024 ** 3 : null }) }}><h2 className="flex items-center gap-2 font-semibold"><FolderOpen size={19} />{t('storageApp.planVolume')}</h2><p className="mt-1 text-xs text-foreground/45">{t('storageApp.planVolumeHint')}</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label={t('storageApp.backend')}><select value={volumeForm.backend} onChange={(event) => setVolumeForm((current) => ({ ...current, backend: event.target.value }))} className="mt-1 w-full rounded-xl border border-foreground/10 bg-foreground/5 px-3 py-2 text-sm outline-none focus:border-cyan-400/40"><option value="btrfs">Btrfs</option><option value="zfs">ZFS</option></select></Field><Field label={t('storageApp.poolOrMount')}><input required value={volumeForm.pool} onChange={(event) => setVolumeForm((current) => ({ ...current, pool: event.target.value }))} className="mt-1 w-full rounded-xl border border-foreground/10 bg-foreground/5 px-3 py-2 text-sm outline-none focus:border-cyan-400/40" placeholder={volumeForm.backend === 'btrfs' ? '/srv/rumahl/storage' : 'tank'} /></Field><Field label={t('storageApp.volumeName')}><input required value={volumeForm.name} onChange={(event) => setVolumeForm((current) => ({ ...current, name: event.target.value }))} className="mt-1 w-full rounded-xl border border-foreground/10 bg-foreground/5 px-3 py-2 text-sm outline-none focus:border-cyan-400/40" /></Field><Field label={t('storageApp.quotaGiB')}><input type="number" min="1" value={volumeForm.quota} onChange={(event) => setVolumeForm((current) => ({ ...current, quota: event.target.value }))} className="mt-1 w-full rounded-xl border border-foreground/10 bg-foreground/5 px-3 py-2 text-sm outline-none focus:border-cyan-400/40" /></Field></div><button type="submit" disabled={planning} className="rumahl-primary-button mt-4">{t('storageApp.reviewPlan')}</button></form>
      <form className="rumahl-card p-5" onSubmit={(event) => { event.preventDefault(); void reviewNasPlan({ operation: 'create_share', protocol: shareForm.protocol, name: shareForm.name, path: shareForm.path, read_only: shareForm.readOnly, guest_access: shareForm.guestAccess, principals: shareForm.principals.split(',').map((value) => value.trim()).filter(Boolean) }) }}><h2 className="flex items-center gap-2 font-semibold"><ShareNetwork size={19} />{t('storageApp.planShare')}</h2><p className="mt-1 text-xs text-foreground/45">{t('storageApp.planShareHint')}</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label={t('storageApp.protocol')}><select value={shareForm.protocol} onChange={(event) => setShareForm((current) => ({ ...current, protocol: event.target.value }))} className="mt-1 w-full rounded-xl border border-foreground/10 bg-foreground/5 px-3 py-2 text-sm outline-none focus:border-cyan-400/40"><option value="smb">SMB</option><option value="nfs">NFS</option></select></Field><Field label={t('storageApp.shareName')}><input required value={shareForm.name} onChange={(event) => setShareForm((current) => ({ ...current, name: event.target.value }))} className="mt-1 w-full rounded-xl border border-foreground/10 bg-foreground/5 px-3 py-2 text-sm outline-none focus:border-cyan-400/40" /></Field><Field label={t('storageApp.sharePath')}><input required value={shareForm.path} onChange={(event) => setShareForm((current) => ({ ...current, path: event.target.value }))} className="mt-1 w-full rounded-xl border border-foreground/10 bg-foreground/5 px-3 py-2 text-sm outline-none focus:border-cyan-400/40" placeholder="/srv/rumahl/storage/family" /></Field><Field label={t('storageApp.principals')}><input value={shareForm.principals} onChange={(event) => setShareForm((current) => ({ ...current, principals: event.target.value }))} className="mt-1 w-full rounded-xl border border-foreground/10 bg-foreground/5 px-3 py-2 text-sm outline-none focus:border-cyan-400/40" /></Field></div><div className="mt-4 flex flex-wrap gap-4 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={shareForm.readOnly} onChange={(event) => setShareForm((current) => ({ ...current, readOnly: event.target.checked }))} />{t('storageApp.shareReadOnly')}</label><label className="flex items-center gap-2"><input type="checkbox" checked={shareForm.guestAccess} onChange={(event) => setShareForm((current) => ({ ...current, guestAccess: event.target.checked }))} />{t('storageApp.guestAccess')}</label></div><button type="submit" disabled={planning} className="rumahl-primary-button mt-4">{t('storageApp.reviewPlan')}</button></form>
    </div>
    <div className="mt-5"><h2 className="mb-3 text-sm font-semibold">{t('storageApp.storageJobs')}</h2><div className="grid gap-3 md:grid-cols-2">{jobs.slice(0, 6).map((job) => <article key={job.id} className="rumahl-card p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{job.resource}</h3><p className="text-xs text-foreground/45">{t(`storageApp.job_${job.kind}`)}</p></div><span className={`rounded-full px-2 py-1 text-[10px] ${job.status === 'failed' ? 'bg-destructive/10 text-destructive' : job.status === 'completed' ? 'bg-success/10 text-success' : 'bg-cyan-500/10 text-cyan-300'}`}>{t(`storageApp.jobStatus_${job.status}`)}</span></div><p className="mt-3 text-xs text-foreground/55">{job.error || job.message}</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-foreground/8"><div className="h-full rounded-full bg-cyan-400" style={{ width: `${Math.min(job.progress_percent, 100)}%` }} /></div></article>)}{!jobs.length && <Empty text={t('storageApp.noJobs')} />}</div></div>
    {plan && createPortal(<div className="fixed inset-0 z-[120] grid place-items-center bg-black/60 p-4" onMouseDown={() => setPlan(null)}><div className="rumahl-card max-h-[85vh] w-full max-w-2xl overflow-y-auto p-6" onMouseDown={(event) => event.stopPropagation()}><header className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-warning">{t('storageApp.planOnly')}</p><h2 className="mt-1 text-xl font-semibold">{plan.summary}</h2></div><button type="button" onClick={() => setPlan(null)} className="rounded-xl p-2 hover:bg-foreground/7"><X size={18} /></button></header><div className="mt-5 rounded-2xl border border-amber-400/20 bg-warning/8 p-4"><p className="text-sm font-semibold">{plannedRequest ? t('storageApp.writeWarning') : t('storageApp.notExecuted')}</p><p className="mt-1 text-xs text-foreground/55">{plannedRequest ? t('storageApp.writeSafety') : t('storageApp.planSafety')}</p></div><div className="mt-5 space-y-2">{plan.warnings.map((warning) => <p key={warning} className="flex gap-2 text-sm text-foreground/65"><WarningCircle size={17} className="mt-0.5 shrink-0 text-warning" />{warning}</p>)}</div><div className="mt-5 space-y-3">{plan.commands.map((command, index) => <div key={`${command.program}-${index}`} className="rounded-2xl bg-black/20 p-4"><p className="text-xs text-foreground/45">{command.purpose}</p><code className="mt-2 block break-all text-xs text-cyan-200">{[command.program, ...command.arguments].join(' ')}</code></div>)}</div><div className="mt-5 rounded-2xl border border-foreground/8 p-4"><span className="text-xs text-foreground/45">{plannedRequest ? t('storageApp.typeConfirmation') : t('storageApp.futureConfirmation')}</span><code className="mt-1 block text-sm font-semibold">{plan.confirmation_phrase}</code>{plannedRequest && <><input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} className="mt-3 w-full rounded-xl border border-foreground/10 bg-foreground/5 px-3 py-2 text-sm outline-none focus:border-amber-400/50" autoComplete="off" /><button type="button" disabled={planning || confirmation !== plan.confirmation_phrase} onClick={() => void executePlan()} className="rumahl-primary-button mt-3 w-full">{t('storageApp.executeWrite')}</button></>}</div></div></div>, document.body)}
  </div>
  </section>
}

function Summary({ icon: Icon, label, value, warning = false }: { icon: typeof HardDrive; label: string; value: string; warning?: boolean }) { return <div className="rumahl-card p-4"><Icon size={20} className={warning ? 'text-warning' : 'text-accent'} /><p className="mt-3 text-xl font-semibold">{value}</p><p className="text-xs text-foreground/40">{label}</p></div> }
function Metric({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] uppercase tracking-wide text-foreground/35">{label}</p><p className="mt-1 truncate font-medium">{value}</p></div> }
function Empty({ text }: { text: string }) { return <div className="rumahl-card p-8 text-center text-sm text-foreground/40">{text}</div> }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-xs text-foreground/55"><span className="mb-1 block">{label}</span>{children}</label> }
