use std::{sync::Arc, time::Instant};

use axum::{
    extract::State,
    http::StatusCode,
    response::IntoResponse,
    routing::{get, post},
    Json, Router,
};
use chrono::Utc;
use serde::{Deserialize, Serialize};
use tokio::sync::RwLock;
use tower_http::cors::CorsLayer;
use tracing::info;
use uuid::Uuid;

#[derive(Clone)]
struct AppState {
    history: Arc<RwLock<Vec<ChatMessage>>>,
    started_at: Arc<Instant>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct ChatMessage {
    id: String,
    role: String,
    content: String,
    timestamp: String,
}

#[derive(Debug, Deserialize)]
struct ChatRequest {
    message: String,
    #[serde(default)]
    #[allow(dead_code)]
    context: serde_json::Value,
}

#[derive(Debug, Deserialize)]
struct AutomateRequest {
    description: String,
    #[serde(default)]
    entities: Vec<String>,
}

// ─── Handlers ────────────────────────────────────────────────────────────────

async fn health(State(state): State<AppState>) -> Json<serde_json::Value> {
    Json(serde_json::json!({
        "service": "iora-assist",
        "status": "healthy",
        "uptime_seconds": state.started_at.elapsed().as_secs(),
        "timestamp": Utc::now().to_rfc3339(),
        "ai_backend": "not_configured",
    }))
}

async fn chat(State(state): State<AppState>, Json(req): Json<ChatRequest>) -> impl IntoResponse {
    let user_msg = ChatMessage {
        id: Uuid::new_v4().to_string(),
        role: "user".to_string(),
        content: req.message.clone(),
        timestamp: Utc::now().to_rfc3339(),
    };
    state.history.write().await.push(user_msg);

    (
        StatusCode::NOT_IMPLEMENTED,
        Json(serde_json::json!({
            "error": "AI backend not configured",
            "message": "iora-assist is a skeleton service. To enable AI chat, configure an AI provider (e.g., OpenAI, Ollama, or a local LLM) and set the ASSIST_AI_BACKEND_URL and ASSIST_AI_API_KEY environment variables.",
            "your_message": req.message,
            "hint": "See ARCHITECTURE.md for details on integrating an AI backend.",
        })),
    )
}

async fn chat_history(State(state): State<AppState>) -> Json<serde_json::Value> {
    let history = state.history.read().await.clone();
    Json(serde_json::json!({
        "messages": history,
        "total": history.len(),
    }))
}

async fn suggestions() -> impl IntoResponse {
    (
        StatusCode::NOT_IMPLEMENTED,
        Json(serde_json::json!({
            "error": "AI backend not configured",
            "message": "Automation suggestions require an AI backend. Configure ASSIST_AI_BACKEND_URL to enable this feature.",
            "hint": "Suggestions are generated by analysing your Home Assistant entity history and usage patterns.",
        })),
    )
}

async fn create_automation(Json(req): Json<AutomateRequest>) -> impl IntoResponse {
    (
        StatusCode::NOT_IMPLEMENTED,
        Json(serde_json::json!({
            "error": "AI backend not configured",
            "message": "Natural-language automation creation requires an AI backend.",
            "your_description": req.description,
            "entities_mentioned": req.entities,
            "hint": "Configure ASSIST_AI_BACKEND_URL and ASSIST_AI_API_KEY to enable this feature.",
        })),
    )
}

async fn insights() -> impl IntoResponse {
    (
        StatusCode::NOT_IMPLEMENTED,
        Json(serde_json::json!({
            "error": "AI backend not configured",
            "message": "Home insights require an AI backend that can analyse entity history data.",
            "hint": "Configure ASSIST_AI_BACKEND_URL to enable AI-generated insights about your smart home.",
        })),
    )
}

// ─── Main ─────────────────────────────────────────────────────────────────────

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    dotenv::dotenv().ok();
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| "iora_assist=debug,info".parse().unwrap()),
        )
        .init();

    let state = AppState {
        history: Arc::new(RwLock::new(Vec::new())),
        started_at: Arc::new(Instant::now()),
    };

    let app = Router::new()
        .route("/health", get(health))
        .route("/api/assist/chat", post(chat))
        .route("/api/assist/history", get(chat_history))
        .route("/api/assist/suggestions", get(suggestions))
        .route("/api/assist/automate", post(create_automation))
        .route("/api/assist/insights", get(insights))
        .layer(CorsLayer::permissive())
        .with_state(state);

    let addr = std::net::SocketAddr::from(([0, 0, 0, 0], 8092));
    info!("iora-assist listening on {}", addr);
    let listener = tokio::net::TcpListener::bind(addr).await?;
    axum::serve(listener, app).await?;

    Ok(())
}
