# RAUC Update Configuration for rumahl OS

[system]
compatible=rumahl-os
bootloader=grub
bundle-formats=-plain
max-bundle-download-size=2147483648
statusfile=/var/lib/rauc/status

[keyring]
path=/etc/rauc/keyring.pem
use-bundle-signing-time=true

[slot.bootloader.0]
device=/dev/sda1
type=vfat
parent=rootfs.0

[slot.rootfs.0]
device=/dev/sda2
type=ext4
bootname=A
readonly=false

[slot.rootfs.1]
device=/dev/sda3
type=ext4
bootname=B
readonly=false
