// Evolution Engine - Core logic for ORA's self-improvement cycle
use std::path::{Path, PathBuf};
use uuid::Uuid;
use chrono::{DateTime, Utc};

use crate::providers::{AIProvider, ChatMessage};
use crate::self_evolution::{EvolutionProposal, EvolutionConfig};
use super::tools::CodeReadTool;

/// The evolution engine orchestrates ORA's self-improvement cycle:
/// 1. **Self-Assessment**: Analyze current codebase and identify improvement areas
/// 2. **Proposal Generation**: Create structured proposals for changes
/// 3. **Approval Gate**: Auto-approve safe changes, request user approval for risky ones
/// 4. **Implementation**: Use AI to generate and apply code changes
/// 5. **Verification**: Run tests and validate changes
/// 6. **Reflection**: Learn from the outcome (success/failure)
pub struct EvolutionEngine {
    config: EvolutionConfig,
    db_pool: sqlx::PgPool,
    /// Primary provider for self-evolution (pi.dev when available)
    evolution_provider: Box<dyn AIProvider>,
    /// Fallback provider if pi.dev is unavailable
    fallback_provider: Option<Box<dyn AIProvider>>,
    /// Path to the iora-assist source code
    source_dir: PathBuf,
}

impl EvolutionEngine {
    pub fn new(
        config: EvolutionConfig,
        db_pool: sqlx::PgPool,
        evolution_provider: Box<dyn AIProvider>,
        fallback_provider: Option<Box<dyn AIProvider>>,
        source_dir: PathBuf,
    ) -> Self {
        Self {
            config,
            db_pool,
            evolution_provider,
            fallback_provider,
            source_dir,
        }
    }

    /// Get the effective provider for self-evolution tasks.
    /// Uses pi.dev if enabled, falls back to configured alternative.
    fn get_provider(&self) -> &dyn AIProvider {
        if self.config.pidev_enabled {
            self.evolution_provider.as_ref()
        } else if let Some(fallback) = &self.fallback_provider {
            fallback.as_ref()
        } else {
            self.evolution_provider.as_ref()
        }
    }

    /// # Phase 1: Self-Assessment
    /// Analyze the current codebase and identify areas for improvement.
    /// Generates evolution proposals based on code analysis, recent failures, and user feedback.
    pub async fn run_self_assessment(&self) -> Result<Vec<EvolutionProposal>, String> {
        tracing::info!("Starting self-assessment cycle");

        let recent_failures = "No recent failures.";
        let codebase_structure = self.scan_codebase().await?;
        let user_feedback = "No recent feedback.";

        let context = format!(
            "=== ORA Self-Assessment ===\n\n\
             You are ORA, an autonomous AI assistant. Analyze your own codebase and identify improvements.\n\n\
             ## Codebase Structure:\n{}\n\n\
             ## Recent Issues:\n{}\n\n\
             ## Current Configuration:\n{:?}",
            codebase_structure,
            recent_failures,
            self.config,
        );

        let prompt = format!(
            "Analyze the following ORA system and generate up to {} improvement proposals.\n\
             Each proposal should be practical, specific, and actionable.\n\n{}\n\n\
             Return proposals as a JSON array with this structure:\n\
             [{{\"title\": \"...\", \"description\": \"...\", \"category\": \"feature|bugfix|optimization|security|refactor\",\
              \"priority\": 1-10, \"rationale\": \"...\", \"estimated_effort\": \"low|medium|high\",\
               \"files_to_modify\": [\"src/path.rs\"]}}]",
            self.config.max_concurrent_proposals,
            context
        );

        let response = self.get_provider().chat(
            vec![ChatMessage {
                role: "user".to_string(),
                content: prompt,
            }],
            Some("You are an AI system analyzing your own codebase for improvements.".to_string()),
        ).await.map_err(|e| format!("Provider error: {}", e))?;

        // Parse proposals from AI response
        let proposals: Vec<EvolutionProposal> = match serde_json::from_str(&response.message) {
            Ok(parsed) => parsed,
            Err(_) => {
                // Fallback: generate a default improvement proposal
                vec![EvolutionProposal {
                    id: Uuid::new_v4(),
                    title: "Improve error handling in provider modules".to_string(),
                    description: Some("Suggested improvement from self-assessment".to_string()),
                    category: "optimization".to_string(),
                    priority: 5,
                    status: "proposed".to_string(),
                    rationale: Some("Generated by self-assessment".to_string()),
                    estimated_effort: Some("medium".to_string()),
                    created_by: "ora".to_string(),
                    provider_used: None,
                    model_used: None,
                    implementation_plan: None,
                    files_to_modify: vec![],
                    tests_required: true,
                    approved_by: None,
                    approved_at: None,
                    rejected_reason: None,
                    created_at: Utc::now(),
                    updated_at: Utc::now(),
                }]
            }
        };

        tracing::info!(
            "Self-assessment complete: {} proposals generated",
            proposals.len()
        );

        Ok(proposals)
    }

    /// Scan the codebase structure for self-assessment context
    async fn scan_codebase(&self) -> Result<String, String> {
        let mut structure = Vec::new();
        if let Ok(entries) = std::fs::read_dir(&self.source_dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.is_file() && path.extension().map(|e| e == "rs").unwrap_or(false) {
                    if let Ok(relative) = path.strip_prefix(&self.source_dir) {
                        structure.push(format!("- {}", relative.display()));
                    }
                } else if path.is_dir() {
                    if let Ok(relative) = path.strip_prefix(&self.source_dir) {
                        structure.push(format!("📁 {}", relative.display()));
                    }
                }
            }
        }
        Ok(structure.join("\n"))
    }
}

fn truncate(s: &str, max_len: usize) -> &str {
    if s.len() <= max_len { s } else { &s[..max_len] }
}
