<?php
/**
 * rumahl Status — single entry point (website root).
 *
 * Routes backend paths itself and serves the static frontend for everything
 * else, so the web root exposes exactly ONE PHP file (this router) and no
 * /api mount is needed for the backend:
 *
 *   /api/*            → backend API (kept for compatibility with the app)
 *   /rss, /feed       → RSS feed
 *   /favicon.svg      → status-colored favicon
 *   /status.json      → statuspage.io-style output
 *   /cron.php         → HTTP cron (cron.php?key=…)
 *   /upgrade.php      → upgrade tool (upgrade.php?key=…)
 *   /install.php      → one-time web installer
 *   everything else   → static files from ./frontend (Next.js export),
 *                       /404.html when nothing matches
 *
 * Generated by backend/root/build.sh — do not edit the router by hand
 * after build.sh has copied it (index.php + .htaccess are static sources).
 */

declare(strict_types=1);

$path = parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH) ?: '/';
$path = rawurldecode($path);

/* ── Backend routes ─────────────────────────────────────────────── */
$isBackend =
    str_starts_with($path, '/api') ||
    in_array($path, ['/rss', '/feed', '/favicon.svg', '/status.json', '/cron.php', '/upgrade.php', '/install.php'], true);

if ($isBackend) {
    // api.php/cron.php/… live in ./src — not directly reachable (see .htaccess).
    if (str_starts_with($path, '/api')) {
        require __DIR__ . '/src/api.php';
    }
    if (in_array($path, ['/rss', '/feed', '/favicon.svg', '/status.json'], true)) {
        require __DIR__ . '/src/api.php';
    }
    if ($path === '/cron.php') {
        require __DIR__ . '/src/cron.php';
    }
    if ($path === '/upgrade.php') {
        require __DIR__ . '/src/upgrade.php';
    }
    if ($path === '/install.php') {
        require __DIR__ . '/src/install.php';
    }
}

/* ── Static frontend ────────────────────────────────────────────── */

/** Serve a file with a sane Content-Type. */
function serve_static(string $file, bool $immutable = false): never
{
    $mime = [
        'html' => 'text/html; charset=utf-8',
        'js' => 'text/javascript',
        'css' => 'text/css',
        'svg' => 'image/svg+xml',
        'png' => 'image/png',
        'jpg' => 'image/jpeg',
        'jpeg' => 'image/jpeg',
        'webp' => 'image/webp',
        'ico' => 'image/x-icon',
        'woff2' => 'font/woff2',
        'woff' => 'font/woff',
        'json' => 'application/json',
        'webmanifest' => 'application/manifest+json',
        'txt' => 'text/plain',
        'xml' => 'application/xml',
        'map' => 'application/json',
    ];
    $ext = strtolower(pathinfo($file, PATHINFO_EXTENSION));
    header('Content-Type: ' . ($mime[$ext] ?? 'application/octet-stream'));
    header('Content-Length: ' . (string) filesize($file));
    header('Cache-Control: ' . ($immutable ? 'public, max-age=31536000, immutable' : 'no-cache'));
    readfile($file);
    exit;
}

function serve_frontend(string $path): never
{
    $base = realpath(__DIR__ . '/frontend');
    if ($base === false) {
        http_response_code(503);
        header('Content-Type: text/plain; charset=utf-8');
        echo 'Frontend build missing — upload the contents of frontend/out/ as ./frontend/ (see UPDATE.md).';
        exit;
    }

    $clean = '/' . ltrim(str_replace('\\', '/', $path), '/');
    $candidates = [];
    if ($clean === '/') {
        $candidates[] = '/index.html';
    } else {
        $candidates[] = $clean;
        $candidates[] = rtrim($clean, '/') . '/index.html';
        $candidates[] = $clean . '.html';
    }

    foreach ($candidates as $candidate) {
        $file = realpath($base . $candidate);
        if ($file !== false && is_file($file) && str_starts_with($file, $base . DIRECTORY_SEPARATOR)) {
            serve_static($file, immutable: str_contains($clean, '/_next/'));
        }
    }

    http_response_code(404);
    $notFound = realpath($base . '/404.html');
    if ($notFound !== false && is_file($notFound)) {
        serve_static($notFound);
    }
    header('Content-Type: text/plain; charset=utf-8');
    echo '404 Not Found';
    exit;
}

serve_frontend($path);
